fix(merge_issues): Fixes after merge - fixed AddUnitByChat
raccoongang/socraticqs2 pull request #70
Opened 2017-08-16 16:12 UTC by alexbojko

### [ISSUE] 
After merging branches add unit by chat functionality was broken

### [SOLUTION]
Fixed AddUnitByChat - returned it to old flow (no chat JS init), added ChatNoJSInit view class to use it when we don't need JS init process.

2017-08-16 17:10 UTC, rimikt commented on mysite/chat/views.py
> +class ChatNoJSInit(object):
Add docstring please.

2017-08-16 17:10 UTC, rimikt commented on mysite/chat/views.py
> +    def get_or_init_chat(self, enroll_code, chat_id):
Same as above.

2017-08-16 17:10 UTC, rimikt commented on mysite/chat/views.py
> +            chat = self.get_chat(
This line w/o indentations will be more than 120 chars?

2017-08-16 17:10 UTC, rimikt commented on mysite/chat/views.py
> +            next_point = None
Do we need this extra variable?

2017-08-18 11:01 UTC, cmltaWt0 approved these changes

2017-08-18 11:01 UTC, rimikt commented
Tests are failed.

2017-08-18 11:02 UTC, cmltaWt0 requested changes
Tests are failed.
Please look

2021-05-27 08:42 UTC, closed without merging